### ISSUE TITLE
validate urls on new

### ISSUE THREAD

**Issue by kyleterry** [kyleterry/sufr#19]
- strip whitespace
- check if it's a URL
- content-type

**Comment by kyleterry** [comment]
not validating URLs just leads to a panic:

```
2016/02/06 01:12:57 stderr: 2016/02/06 01:12:57 http: panic serving 127.0.0.1:53962: runtime error: invalid memory address or nil pointer dereference
2016/02/06 01:12:57 stderr: goroutine 24 [running]:
2016/02/06 01:12:57 stderr: net/http.(*conn).serve.func1(0xc8201148f0, 0xce5bb8, 0xc820078370)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.getPageTitle(0xc8201dd3e0, 0xd, 0x0, 0x0, 0x0, 0x0)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/utils.go:14 +0x60
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.(*Sufr).urlSubmitHandler(0x716eb8, 0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/handlers.go:41 +0xc0
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.(*Sufr).(github.com/kyleterry/sufr/app.urlSubmitHandler)-fm(0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/app.go:29 +0x3e
2016/02/06 01:12:57 stderr: net/http.HandlerFunc.ServeHTTP(0xc8201bc3b0, 0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82007c460, 0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/vendor/github.com/gorilla/mux/mux.go:103 +0x270
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.Sufr.ServeHTTP(0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/app.go:48 +0x41
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.(*Sufr).ServeHTTP(0x716eb8, 0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     <autogenerated>:1 +0xab
2016/02/06 01:12:57 stderr: net/http.serverHandler.ServeHTTP(0xc82009cfc0, 0xce9d38, 0xc820114b00, 0xc820135b20)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
2016/02/06 01:12:57 stderr: net/http.(*conn).serve(0xc8201148f0)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
2016/02/06 01:12:57 stderr: created by net/http.(*Server).Serve
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
2016/02/06 01:12:57 stderr: 2016/02/06 01:12:57 http: panic serving 127.0.0.1:53966: runtime error: invalid memory address or nil pointer dereference
2016/02/06 01:12:57 stderr: goroutine 25 [running]:
2016/02/06 01:12:57 stderr: net/http.(*conn).serve.func1(0xc820114bb0, 0xce5bb8, 0xc8200783e0)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.getPageTitle(0xc8201dd5e0, 0xd, 0x0, 0x0, 0x0, 0x0)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/utils.go:14 +0x60
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.(*Sufr).urlSubmitHandler(0x716eb8, 0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/handlers.go:41 +0xc0
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.(*Sufr).(github.com/kyleterry/sufr/app.urlSubmitHandler)-fm(0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/app.go:29 +0x3e
2016/02/06 01:12:57 stderr: net/http.HandlerFunc.ServeHTTP(0xc8201bc3b0, 0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82007c460, 0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/vendor/github.com/gorilla/mux/mux.go:103 +0x270
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.Sufr.ServeHTTP(0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     /Users/kyleterry/src/go/src/github.com/kyleterry/sufr/app/app.go:48 +0x41
2016/02/06 01:12:57 stderr: github.com/kyleterry/sufr/app.(*Sufr).ServeHTTP(0x716eb8, 0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     <autogenerated>:1 +0xab
2016/02/06 01:12:57 stderr: net/http.serverHandler.ServeHTTP(0xc82009cfc0, 0xce9d38, 0xc820114c60, 0xc820135ce0)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
2016/02/06 01:12:57 stderr: net/http.(*conn).serve(0xc820114bb0)
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
2016/02/06 01:12:57 stderr: created by net/http.(*Server).Serve
2016/02/06 01:12:57 stderr:     /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
```

**Comment by kyleterry** [comment]
Use `github.com/asaskevich/govalidator`:

```
if govalidator.IsURL(urlstring) {
...
}
```

Then I will need to use sessions (gorilla/session) to flash a message back to the user and kick it back to the new view if it errors.

**Comment by kyleterry** [comment]
Done
